/*
 * This file was autogenerated by OSQP on Sun Sep  7 17:07:52 2025
 * 
 * This file contains the configuration options needed by OSQP.
 */

#ifndef OSQP_CONFIGURE_H
#define OSQP_CONFIGURE_H

#define OSQP_ALGEBRA_BUILTIN
#define OSQP_EMBEDDED_MODE 2

#endif /* ifndef OSQP_CONFIGURE_H */
