/*
 * This file was autogenerated by OSQP on Sun Sep  7 17:07:52 2025
 * 
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef WORKSPACE_H
#define WORKSPACE_H

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPSolver solver;
  extern OSQPFloat sol_x[4];
  extern OSQPFloat sol_y[2];

#ifdef __cplusplus
}
#endif

#endif /* ifndef WORKSPACE_H */
