
/*
Auto-generated by CVXPYgen on September 07, 2025 at 17:14:23.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_initialState(0, 0.32730946282591782959);
  cpg_update_referenceState(0, -0.42394661766599489594);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<2; i++) {
    printf("controlAction[%d] = %f\n", i, CPG_Result.prim->controlAction[i]);
  }

  return 0;

}
