
/*
Auto-generated by CVXPYgen on September 07, 2025 at 17:07:52.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[5] = {
(cpg_float)-0.43233332595261331210,
(cpg_float)-0.93240193464568665860,
(cpg_float)0.04382859614515311614,
(cpg_float)-0.77602069197485212815,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_l_map_i[4] = {
0,
2,
1,
3,
};
cpg_int canon_l_map_p[3] = {
0,
2,
4,
};
cpg_float canon_l_map_x[4] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_l_map = {canon_l_map_p, canon_l_map_i, canon_l_map_x, 4};

cpg_int canon_u_map_i[4] = {
0,
2,
1,
3,
};
cpg_int canon_u_map_p[3] = {
0,
2,
4,
};
cpg_float canon_u_map_x[4] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_u_map = {canon_u_map_p, canon_u_map_i, canon_u_map_x, 4};

// Canonical parameters
cpg_int canon_P_i[4] = {
0,
1,
2,
3,
};
cpg_int canon_P_p[5] = {
0,
1,
2,
3,
4,
};
cpg_float canon_P_x[4] = {
(cpg_float)2.00000000000000000000,
(cpg_float)2.00000000000000000000,
(cpg_float)0.00200000000000000004,
(cpg_float)0.00200000000000000004,
};
cpg_csc canon_P = {canon_P_p, canon_P_i, canon_P_x, 4};

cpg_float canon_q[4] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_A_i[4] = {
0,
1,
0,
1,
};
cpg_int canon_A_p[5] = {
0,
1,
2,
3,
4,
};
cpg_float canon_A_x[4] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-0.04000000000000000083,
(cpg_float)-0.04000000000000000083,
};
cpg_csc canon_A = {canon_A_p, canon_A_i, canon_A_x, 4};

cpg_float canon_l[2] = {
(cpg_float)0.47616192209776642130,
(cpg_float)0.15638124267083453045,
};

cpg_float canon_u[2] = {
(cpg_float)0.47616192209776642130,
(cpg_float)0.15638124267083453045,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.P = &canon_P,
.q = (cpg_float *) &canon_q,
.d = 0.00000000000000000000,
.A = &canon_A,
.l = (cpg_float *) &canon_l,
.u = (cpg_float *) &canon_u,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.P = 1,
.q = 1,
.d = 1,
.A = 1,
.l = 1,
.u = 1,
};

// User-defined variables
// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.controlAction = (cpg_float *) &sol_x + 2,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = "unknown",
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.info = &CPG_Info,
};

// Struct containing solver settings
Canon_Settings_t Canon_Settings = {
.max_iter = 4000,
.eps_abs = 1e-3,
.eps_rel = 1e-3,
.eps_prim_inf = 1e-4,
.eps_dual_inf = 1e-4,
.scaled_termination = 0,
.check_termination = 25,
.warm_starting = 1,
};
