
/*
Auto-generated by CVXPYgen on September 05, 2025 at 21:34:39.
Content: Type definitions and variable declarations.
*/

#include "scs.h"

#ifndef CPG_TYPES_H
# define CPG_TYPES_H

typedef scs_float cpg_float;
typedef scs_int cpg_int;

// Compressed sparse column matrix
typedef struct {
  cpg_int      *p;
  cpg_int      *i;
  cpg_float    *x;
  cpg_int      nnz;
} cpg_csc;

// Canonical parameters
typedef struct {
  cpg_csc      *P;         // Canonical parameter P
  cpg_float    *c;         // Canonical parameter c
  cpg_float    d;          // Canonical parameter d
  cpg_csc      *A;         // Canonical parameter A
  cpg_float    *b;         // Canonical parameter b
} Canon_Params_t;

// Flags indicating outdated canonical parameters
typedef struct {
  int        P;            // Bool, if canonical parameter P outdated
  int        c;            // Bool, if canonical parameter c outdated
  int        d;            // Bool, if canonical parameter d outdated
  int        A;            // Bool, if canonical parameter A outdated
  int        b;            // Bool, if canonical parameter b outdated
} Canon_Outdated_t;

// Primal solution
typedef struct {
  cpg_float    *controlAction;   // Your variable controlAction
} CPG_Prim_t;

// Solver information
typedef struct {
  cpg_float    obj_val;    // Objective function value
  cpg_int      iter;       // Number of iterations
  char         *status;    // Solver status
  cpg_float    pri_res;    // Primal residual
  cpg_float    dua_res;    // Dual residual
} CPG_Info_t;

// Solution and solver information
typedef struct {
  CPG_Prim_t *prim;        // Primal solution
  CPG_Info_t *info;        // Solver info
} CPG_Result_t;

// Parameter deltas
typedef struct {
  cpg_float    *initialState;   // Delta of your parameter initialState
  cpg_float    *referenceState;   // Delta of your parameter referenceState
} CPG_Delta_t;

#endif // ifndef CPG_TYPES_H

// Vector containing flattened user-defined parameters
extern cpg_float cpg_params_vec[5];

// Sparse mappings from user-defined to canonical parameters
extern cpg_csc canon_b_map;

// Canonical parameters
extern cpg_csc canon_P;
extern cpg_float canon_c[4];
extern cpg_csc canon_A;
extern cpg_float canon_b[2];

// Struct containing canonical parameters
extern Canon_Params_t Canon_Params;

// Struct containing flags for outdated canonical parameters
extern Canon_Outdated_t Canon_Outdated;

// Struct containing primal solution
extern CPG_Prim_t CPG_Prim;

// Struct containing solver info
extern CPG_Info_t CPG_Info;

// Struct containing solution and info
extern CPG_Result_t CPG_Result;

// SCS matrix P
extern ScsMatrix scs_P;

// SCS matrix A
extern ScsMatrix scs_A;

// Struct containing SCS data
extern ScsData Scs_D;

// Struct containing SCS cone data
extern ScsCone Scs_K;

// Struct containing SCS settings
extern ScsSettings Canon_Settings;

// SCS solution
extern cpg_float scs_x[4];
extern cpg_float scs_y[2];
extern cpg_float scs_s[2];

// Struct containing SCS solution
extern ScsSolution Scs_Sol;

// Struct containing SCS information
extern ScsInfo Scs_Info;

// Pointer to struct containing SCS workspace
extern ScsWork* Scs_Work;
