/*
 * This file was autogenerated by OSQP on Fri Aug 29 14:29:56 2025
 * 
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef WORKSPACE_H
#define WORKSPACE_H

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPSolver solver;
  extern OSQPFloat sol_x[2];
  extern OSQPFloat sol_y[1];

#ifdef __cplusplus
}
#endif

#endif /* ifndef WORKSPACE_H */
