/*
 * This file was autogenerated by OSQP on Fri Aug 29 14:29:56 2025
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "algebra_impl.h"
#include "qdldl_interface.h"

/* Define the settings structure */
OSQPSettings settings = {
  0,
  OSQP_DIRECT_SOLVER,
  1,
  0,
  0,
  1,
  10,
  0,
  (OSQPFloat)0.10000000000000000555,
  1,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)1.60000000000000008882,
  20,
  10,
  (OSQPFloat)0.14999999999999999445,
  1,
  1,
  50,
  (OSQPFloat)0.40000000000000002220,
  (OSQPFloat)5.00000000000000000000,
  4000,
  (OSQPFloat)0.00100000000000000002,
  (OSQPFloat)0.00100000000000000002,
  (OSQPFloat)0.00010000000000000000,
  (OSQPFloat)0.00010000000000000000,
  0,
  25,
  1,
  (OSQPFloat)10000000000.00000000000000000000,
  (OSQPFloat)0.00000100000000000000,
  3,
};

/* Define the solution structure */
OSQPFloat sol_x[2];
OSQPFloat sol_y[1];
OSQPFloat sol_prim_inf_cert[1];
OSQPFloat sol_dual_inf_cert[2];
OSQPSolution sol = {
  sol_x,
  sol_y,
  sol_prim_inf_cert,
  sol_dual_inf_cert,
};

/* Define the info structure */
OSQPInfo info = {
  "unsolved",
  11,
  0,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  0,
  0,
  (OSQPFloat)0.10000000000000000555,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
};

/* Define the data structure */
OSQPInt data_P_csc_p[3] = {
  0,
  1,
  2,
};
OSQPInt data_P_csc_i[2] = {
  0,
  1,
};
OSQPFloat data_P_csc_x[2] = {
  (OSQPFloat)1.00000000000000000000,
  (OSQPFloat)1.00000000000000000000,
};
OSQPCscMatrix data_P_csc = {
  2,
  2,
  data_P_csc_p,
  data_P_csc_i,
  data_P_csc_x,
  2,
  -1,
};
OSQPMatrix data_P = {
  &data_P_csc,
  1
};
OSQPInt data_A_csc_p[3] = {
  0,
  1,
  2,
};
OSQPInt data_A_csc_i[2] = {
  0,
  0,
};
OSQPFloat data_A_csc_x[2] = {
  (OSQPFloat)-0.99932332750265073784,
  (OSQPFloat)0.99932332750265073784,
};
OSQPCscMatrix data_A_csc = {
  1,
  2,
  data_A_csc_p,
  data_A_csc_i,
  data_A_csc_x,
  2,
  -1,
};
OSQPMatrix data_A = {
  &data_A_csc,
  0
};
OSQPFloat data_q_val[2] = {
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf data_q = {
  data_q_val,
  2
};
OSQPFloat data_l_val[1] = {
  (OSQPFloat)-0.48766215167474991077,
};
OSQPVectorf data_l = {
  data_l_val,
  1
};
OSQPFloat data_u_val[1] = {
  (OSQPFloat)-0.48766215167474991077,
};
OSQPVectorf data_u = {
  data_u_val,
  1
};
OSQPData data = {
  2,
  1,
  &data_P,
  &data_A,
  &data_q,
  &data_l,
  &data_u
};

/* Define the linear system solver structure */
OSQPInt linsys_L_p[4] = {
  0,
  1,
  2,
  2,
};
OSQPInt linsys_L_i[2] = {
  2,
  2,
};
OSQPFloat linsys_L_x[2] = {
  (OSQPFloat)0.99932232818032262767,
  (OSQPFloat)-0.99932232818032262767,
};
OSQPCscMatrix linsys_L = {
  3,
  3,
  linsys_L_p,
  linsys_L_i,
  linsys_L_x,
  2,
  -1,
};
OSQPFloat linsys_Dinv[3] = {
  (OSQPFloat)0.99999900000100006014,
  (OSQPFloat)0.99999900000100006014,
  (OSQPFloat)-0.49818356580416822688,
};
OSQPInt linsys_P[3] = {
  1,
  0,
  2,
};
OSQPFloat linsys_bp[3];
OSQPFloat linsys_sol[3];
OSQPFloat linsys_rho_inv_vec[1] = {
  (OSQPFloat)0.01000000000000000021,
};
OSQPInt linsys_KKT_p[4] = {
  0,
  1,
  2,
  5,
};
OSQPInt linsys_KKT_i[5] = {
  0,
  1,
  1,
  0,
  2,
};
OSQPFloat linsys_KKT_x[5] = {
  (OSQPFloat)1.00000099999999991773,
  (OSQPFloat)1.00000099999999991773,
  (OSQPFloat)-0.99932332750265073784,
  (OSQPFloat)0.99932332750265073784,
  (OSQPFloat)-0.01000000000000000021,
};
OSQPCscMatrix linsys_KKT = {
  3,
  3,
  linsys_KKT_p,
  linsys_KKT_i,
  linsys_KKT_x,
  5,
  -1,
};
OSQPInt linsys_PtoKKT[2] = {
  1,
  0,
};
OSQPInt linsys_AtoKKT[2] = {
  2,
  3,
};
OSQPInt linsys_rhotoKKT[1] = {
  4,
};
OSQPFloat linsys_D[3] = {
  (OSQPFloat)1.00000099999999991773,
  (OSQPFloat)1.00000099999999991773,
  (OSQPFloat)-2.00729222848971211590,
};
OSQPInt linsys_etree[3] = {
  2,
  2,
  -1,
};
OSQPInt linsys_Lnz[3] = {
  1,
  1,
  0,
};
QDLDL_int   linsys_iwork[9];
QDLDL_bool  linsys_bwork[3];
QDLDL_float linsys_fwork[3];
qdldl_solver linsys = {
  1,
  &name_qdldl,
  &solve_linsys_qdldl,
  &update_settings_linsys_solver_qdldl,
  &warm_start_linsys_solver_qdldl,
  &update_linsys_solver_matrices_qdldl,
  &update_linsys_solver_rho_vec_qdldl,
  1,
  &linsys_L,
  linsys_Dinv,
  linsys_P,
  linsys_bp,
  linsys_sol,
  linsys_rho_inv_vec,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)10.00000000000000000000,
  2,
  1,
  &linsys_KKT,
  linsys_PtoKKT,
  linsys_AtoKKT,
  linsys_rhotoKKT,
  linsys_D,
  linsys_etree,
  linsys_Lnz,
  linsys_iwork,
  linsys_bwork,
  linsys_fwork,
};

OSQPFloat work_rho_vec_val[1] = {
  (OSQPFloat)100.00000000000000000000,
};
OSQPVectorf work_rho_vec = {
  work_rho_vec_val,
  1
};
OSQPFloat work_rho_inv_vec_val[1] = {
  (OSQPFloat)0.01000000000000000021,
};
OSQPVectorf work_rho_inv_vec = {
  work_rho_inv_vec_val,
  1
};
OSQPInt work_constr_type_val[1] = {
  1,
};
OSQPVectori work_constr_type = {
  work_constr_type_val,
  1
};
OSQPFloat work_x_val[2] = {
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf work_x = {
  work_x_val,
  2
};
OSQPFloat work_y_val[1] = {
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf work_y = {
  work_y_val,
  1
};
OSQPFloat work_z_val[1] = {
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf work_z = {
  work_z_val,
  1
};
OSQPFloat   work_xz_tilde_val[3];
OSQPVectorf work_xz_tilde = {
  work_xz_tilde_val,
  3
};
OSQPVectorf work_xtilde_view = {
  work_xz_tilde_val,
  2
};
OSQPVectorf work_ztilde_view = {
  work_xz_tilde_val+2,
  1
};
OSQPFloat   work_x_prev_val[2];
OSQPVectorf work_x_prev = {
  work_x_prev_val,
  2
};
OSQPFloat   work_z_prev_val[1];
OSQPVectorf work_z_prev = {
  work_z_prev_val,
  1
};
OSQPFloat   work_Ax_val[1];
OSQPVectorf work_Ax = {
  work_Ax_val,
  1
};
OSQPFloat   work_Px_val[2];
OSQPVectorf work_Px = {
  work_Px_val,
  2
};
OSQPFloat   work_Aty_val[2];
OSQPVectorf work_Aty = {
  work_Aty_val,
  2
};
OSQPFloat   work_delta_y_val[1];
OSQPVectorf work_delta_y = {
  work_delta_y_val,
  1
};
OSQPFloat   work_Atdelta_y_val[2];
OSQPVectorf work_Atdelta_y = {
  work_Atdelta_y_val,
  2
};
OSQPFloat   work_delta_x_val[2];
OSQPVectorf work_delta_x = {
  work_delta_x_val,
  2
};
OSQPFloat   work_Pdelta_x_val[2];
OSQPVectorf work_Pdelta_x = {
  work_Pdelta_x_val,
  2
};
OSQPFloat   work_Adelta_x_val[1];
OSQPVectorf work_Adelta_x = {
  work_Adelta_x_val,
  1
};
OSQPFloat   work_D_temp_val[2];
OSQPVectorf work_D_temp = {
  work_D_temp_val,
  2
};
OSQPFloat   work_D_temp_A_val[2];
OSQPVectorf work_D_temp_A = {
  work_D_temp_A_val,
  2
};
OSQPFloat   work_E_temp_val[1];
OSQPVectorf work_E_temp = {
  work_E_temp_val,
  1
};

/* Define the scaling structure */
OSQPFloat scaling_D_val[2] = {
  (OSQPFloat)0.70710678118654757274,
  (OSQPFloat)0.70710678118654757274,
};
OSQPVectorf scaling_D = {
  scaling_D_val,
  2
};
OSQPFloat scaling_E_val[1] = {
  (OSQPFloat)1.41325660295005883782,
};
OSQPVectorf scaling_E = {
  scaling_E_val,
  1
};
OSQPFloat scaling_Dinv_val[2] = {
  (OSQPFloat)1.41421356237309492343,
  (OSQPFloat)1.41421356237309492343,
};
OSQPVectorf scaling_Dinv = {
  scaling_Dinv_val,
  2
};
OSQPFloat scaling_Einv_val[1] = {
  (OSQPFloat)0.70758558489136436087,
};
OSQPVectorf scaling_Einv = {
  scaling_Einv_val,
  1
};
OSQPScaling scaling = {
  (OSQPFloat)0.99999999999999977796,
  &scaling_D,
  &scaling_E,
  (OSQPFloat)1.00000000000000022204,
  &scaling_Dinv,
  &scaling_Einv
};

/* Define the workspace structure */
OSQPWorkspace work = {
  &data,
  (LinSysSolver *)&linsys,
  &work_rho_vec,
  &work_rho_inv_vec,
  &work_constr_type,
  &work_x,
  &work_y,
  &work_z,
  &work_xz_tilde,
  &work_xtilde_view,
  &work_ztilde_view,
  &work_x_prev,
  &work_z_prev,
  &work_Ax,
  &work_Px,
  &work_Aty,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  &work_delta_y,
  &work_Atdelta_y,
  &work_delta_x,
  &work_Pdelta_x,
  &work_Adelta_x,
  &work_D_temp,
  &work_D_temp_A,
  &work_E_temp,
  &scaling,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.00000000000000000000,
  0,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
};

/* Define the solver structure */
OSQPSolver solver = {
  &settings,
  &sol,
  &info,
  &work
};
