
/*
Auto-generated by CVXPYgen on September 05, 2025 at 22:18:04.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_initialState(0, -0.27897844324525433723);
  cpg_update_referenceState(0, -1.85445426524695178294);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<2; i++) {
    printf("controlAction[%d] = %f\n", i, CPG_Result.prim->controlAction[i]);
  }

  return 0;

}
