
/*
Auto-generated by CVXPYgen on September 05, 2025 at 22:18:04.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[5] = {
(cpg_float)-0.27897844324525433723,
(cpg_float)1.05338280944213247281,
(cpg_float)-1.85445426524695178294,
(cpg_float)0.87880848621584639613,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_b_map_i[4] = {
0,
2,
1,
3,
};
cpg_int canon_b_map_p[3] = {
0,
2,
4,
};
cpg_float canon_b_map_x[4] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_b_map = {canon_b_map_p, canon_b_map_i, canon_b_map_x, 4};

// Canonical parameters
cpg_int canon_P_i[4] = {
0,
1,
2,
3,
};
cpg_int canon_P_p[5] = {
0,
1,
2,
3,
4,
};
cpg_float canon_P_x[4] = {
(cpg_float)2.00000000000000000000,
(cpg_float)2.00000000000000000000,
(cpg_float)0.00200000000000000004,
(cpg_float)0.00200000000000000004,
};
cpg_csc canon_P = {canon_P_p, canon_P_i, canon_P_x, 4};

cpg_float canon_c[4] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_A_i[4] = {
0,
1,
0,
1,
};
cpg_int canon_A_p[5] = {
0,
1,
2,
3,
4,
};
cpg_float canon_A_x[4] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-0.04000000000000000083,
(cpg_float)-0.04000000000000000083,
};
cpg_csc canon_A = {canon_A_p, canon_A_i, canon_A_x, 4};

cpg_float canon_b[2] = {
(cpg_float)-1.57547582200169733468,
(cpg_float)-0.17457432322628607668,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.P = &canon_P,
.c = (cpg_float *) &canon_c,
.d = 0.00000000000000000000,
.A = &canon_A,
.b = (cpg_float *) &canon_b,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.P = 1,
.c = 1,
.d = 1,
.A = 1,
.b = 1,
};

// User-defined variables
// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.controlAction = (cpg_float *) &scs_x + 2,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = "unknown",
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.info = &CPG_Info,
};

// SCS matrix P
ScsMatrix Scs_P = {
.x = (cpg_float *) &canon_P_x,
.i = (cpg_int *) &canon_P_i,
.p = (cpg_int *) &canon_P_p,
.m = 4,
.n = 4,
};

// SCS matrix A
ScsMatrix Scs_A = {
.x = (cpg_float *) &canon_A_x,
.i = (cpg_int *) &canon_A_i,
.p = (cpg_int *) &canon_A_p,
.m = 2,
.n = 4,
};

// Struct containing SCS data
ScsData Scs_D = {
.m = 2,
.n = 4,
.A = &Scs_A,
.P = &Scs_P,
.b = (cpg_float *) &canon_b,
.c = (cpg_float *) &canon_c,
};

// Struct containing SCS cone data
ScsCone Scs_K = {
.z = 2,
.l = 0,
.bu = SCS_NULL,
.bl = SCS_NULL,
.bsize = 0,
.q = SCS_NULL,
.qsize = 0,
.s = SCS_NULL,
.ssize = 0,
.ep = 0,
.ed = 0,
.p = SCS_NULL,
.psize = 0,
};

// Struct containing SCS settings
ScsSettings Canon_Settings = {
.normalize = 1,
.scale = 0.1,
.adaptive_scale = 1,
.rho_x = 1e-6,
.max_iters = 1e5,
.eps_abs = 1e-4,
.eps_rel = 1e-4,
.eps_infeas = 1e-7,
.alpha = 1.5,
.time_limit_secs = 0,
.verbose = 0,
.warm_start = 0,
.acceleration_lookback = 0,
.acceleration_interval = 1,
.write_data_filename = SCS_NULL,
.log_csv_filename = SCS_NULL,
};

// SCS solution
cpg_float scs_x[4] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};
cpg_float scs_y[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};
cpg_float scs_s[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing SCS solution
ScsSolution Scs_Sol = {
.x = (cpg_float *) &scs_x,
.y = (cpg_float *) &scs_y,
.s = (cpg_float *) &scs_s,
};

// Struct containing SCS information
ScsInfo Scs_Info = {
.iter = 0,
.status = "unknown",
.status_val = 0,
.scale_updates = 0,
.pobj = 0,
.dobj = 0,
.res_pri = 99,
.res_dual = 99,
.gap = 99,
.res_infeas = 99,
.res_unbdd_a = 99,
.res_unbdd_p = 99,
.comp_slack = 99,
.setup_time = 0,
.solve_time = 0,
.scale = 1,
.rejected_accel_steps = 0,
.accepted_accel_steps = 0,
.lin_sys_time = 0,
.cone_time = 0,
.accel_time = 0,
};

// Pointer to struct containing SCS workspace
ScsWork* Scs_Work = 0;
