
/*
Auto-generated by CVXPYgen on September 07, 2025 at 17:14:23.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[5] = {
(cpg_float)0.32730946282591782959,
(cpg_float)0.72869505973250126019,
(cpg_float)-0.42394661766599489594,
(cpg_float)0.34123460612362194189,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_h_map_i[8] = {
4,
4,
0,
2,
1,
3,
4,
4,
};
cpg_int canon_h_map_p[9] = {
0,
1,
2,
4,
6,
7,
8,
8,
8,
};
cpg_float canon_h_map_x[8] = {
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)2.00000000000000000000,
(cpg_float)2.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_h_map = {canon_h_map_p, canon_h_map_i, canon_h_map_x, 8};

// Canonical parameters
cpg_float canon_c[4] = {
(cpg_float)1.00000000000000000000,
(cpg_float)0.00100000000000000002,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float canon_c_conditioning[4] = {
(cpg_float)1.00000000000000000000,
(cpg_float)0.00100000000000000002,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_G_i[8] = {
0,
1,
4,
5,
2,
6,
3,
7,
};
cpg_int canon_G_p[5] = {
0,
2,
4,
6,
8,
};
cpg_float canon_G_x[8] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-0.08000000000000000167,
(cpg_float)2.00000000000000000000,
(cpg_float)0.08000000000000000167,
(cpg_float)-2.00000000000000000000,
};
cpg_csc canon_G = {canon_G_p, canon_G_i, canon_G_x, 8};

cpg_int canon_G_conditioning_i[8] = {
0,
1,
4,
5,
2,
6,
3,
7,
};
cpg_int canon_G_conditioning_p[5] = {
0,
2,
4,
6,
8,
};
cpg_float canon_G_conditioning_x[8] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-0.08000000000000000167,
(cpg_float)2.00000000000000000000,
(cpg_float)0.08000000000000000167,
(cpg_float)-2.00000000000000000000,
};
cpg_csc canon_G_conditioning = {canon_G_conditioning_p, canon_G_conditioning_i, canon_G_conditioning_x, 8};

cpg_float canon_h[8] = {
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.50251216098382545105,
(cpg_float)0.77492090721775863660,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float canon_h_conditioning[8] = {
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.50251216098382545105,
(cpg_float)0.77492090721775863660,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.c = (cpg_float *) &canon_c,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G,
.h = (cpg_float *) &canon_h,
};

Canon_Params_t Canon_Params_conditioning = {
.c = (cpg_float *) &canon_c_conditioning,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G_conditioning,
.h = (cpg_float *) &canon_h_conditioning,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.c = 1,
.d = 1,
.A = 1,
.b = 1,
.G = 1,
.h = 1,
};

// User-defined variables
cpg_float controlAction[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.controlAction = (cpg_float *) &controlAction,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = 0,
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.info = &CPG_Info,
};

// Struct containing solver settings
Canon_Settings_t Canon_Settings = {
.feastol = 1e-8,
.abstol = 1e-8,
.reltol = 1e-8,
.feastol_inacc = 1e-4,
.abstol_inacc = 5e-5,
.reltol_inacc = 5e-5,
.maxit = 100,
};

// ECOS array of SOC dimensions
cpg_int ecos_q[2] = {
4,
4,
};

// ECOS workspace
pwork* ecos_workspace = 0;

// ECOS exit flag
cpg_int ecos_flag = -99;
