
/*
Auto-generated by CVXPYgen on August 29, 2025 at 14:29:56.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[3] = {
(cpg_float)0.32370619460740301943,
(cpg_float)-0.02135651421475607062,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_l_map_i[2] = {
0,
1,
};
cpg_int canon_l_map_p[2] = {
0,
2,
};
cpg_float canon_l_map_x[2] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_l_map = {canon_l_map_p, canon_l_map_i, canon_l_map_x, 2};

cpg_int canon_u_map_i[2] = {
0,
1,
};
cpg_int canon_u_map_p[2] = {
0,
2,
};
cpg_float canon_u_map_x[2] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_u_map = {canon_u_map_p, canon_u_map_i, canon_u_map_x, 2};

// Canonical parameters
cpg_int canon_P_i[2] = {
0,
1,
};
cpg_int canon_P_p[3] = {
0,
1,
2,
};
cpg_float canon_P_x[2] = {
(cpg_float)2.00000000000000000000,
(cpg_float)2.00000000000000000000,
};
cpg_csc canon_P = {canon_P_p, canon_P_i, canon_P_x, 2};

cpg_float canon_q[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_A_i[2] = {
0,
0,
};
cpg_int canon_A_p[3] = {
0,
1,
2,
};
cpg_float canon_A_x[2] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_A = {canon_A_p, canon_A_i, canon_A_x, 2};

cpg_float canon_l[1] = {
(cpg_float)-0.34506270882215911433,
};

cpg_float canon_u[1] = {
(cpg_float)-0.34506270882215911433,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.P = &canon_P,
.q = (cpg_float *) &canon_q,
.d = 0.00000000000000000000,
.A = &canon_A,
.l = (cpg_float *) &canon_l,
.u = (cpg_float *) &canon_u,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.P = 1,
.q = 1,
.d = 1,
.A = 1,
.l = 1,
.u = 1,
};

// User-defined variables
// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.control_action = 0,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = "unknown",
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.info = &CPG_Info,
};

// Struct containing solver settings
Canon_Settings_t Canon_Settings = {
.max_iter = 4000,
.eps_abs = 1e-3,
.eps_rel = 1e-3,
.eps_prim_inf = 1e-4,
.eps_dual_inf = 1e-4,
.scaled_termination = 0,
.check_termination = 25,
.warm_starting = 1,
};
