
/*
Auto-generated by CVXPYgen on August 29, 2025 at 14:29:56.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Initial_state(0.352);
  cpg_update_Reference_state(2.0);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  printf("control_action = %f\n", CPG_Result.prim->control_action);

  return 0;

}
