/*
 * This file was autogenerated by OSQP on Sun Sep  7 18:01:45 2025
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "algebra_impl.h"
#include "qdldl_interface.h"

/* Define the settings structure */
OSQPSettings settings = {
  0,
  OSQP_DIRECT_SOLVER,
  1,
  0,
  0,
  1,
  10,
  0,
  (OSQPFloat)0.10000000000000000555,
  1,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)1.60000000000000008882,
  20,
  10,
  (OSQPFloat)0.14999999999999999445,
  1,
  1,
  50,
  (OSQPFloat)0.40000000000000002220,
  (OSQPFloat)5.00000000000000000000,
  4000,
  (OSQPFloat)0.00100000000000000002,
  (OSQPFloat)0.00100000000000000002,
  (OSQPFloat)0.00010000000000000000,
  (OSQPFloat)0.00010000000000000000,
  0,
  25,
  1,
  (OSQPFloat)10000000000.00000000000000000000,
  (OSQPFloat)0.00000100000000000000,
  3,
};

/* Define the solution structure */
OSQPFloat sol_x[4];
OSQPFloat sol_y[2];
OSQPFloat sol_prim_inf_cert[2];
OSQPFloat sol_dual_inf_cert[4];
OSQPSolution sol = {
  sol_x,
  sol_y,
  sol_prim_inf_cert,
  sol_dual_inf_cert,
};

/* Define the info structure */
OSQPInfo info = {
  "unsolved",
  11,
  0,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
  0,
  0,
  (OSQPFloat)0.10000000000000000555,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
};

/* Define the data structure */
OSQPInt data_P_csc_p[5] = {
  0,
  1,
  2,
  3,
  4,
};
OSQPInt data_P_csc_i[4] = {
  0,
  1,
  2,
  3,
};
OSQPFloat data_P_csc_x[4] = {
  (OSQPFloat)1.00000000000000022204,
  (OSQPFloat)1.00000000000000022204,
  (OSQPFloat)0.64363183417394209673,
  (OSQPFloat)0.64363183417394209673,
};
OSQPCscMatrix data_P_csc = {
  4,
  4,
  data_P_csc_p,
  data_P_csc_i,
  data_P_csc_x,
  4,
  -1,
};
OSQPMatrix data_P = {
  &data_P_csc,
  1
};
OSQPInt data_A_csc_p[5] = {
  0,
  1,
  2,
  3,
  4,
};
OSQPInt data_A_csc_i[4] = {
  0,
  1,
  0,
  1,
};
OSQPFloat data_A_csc_x[4] = {
  (OSQPFloat)-0.98541972343003936263,
  (OSQPFloat)-0.98541972343003936263,
  (OSQPFloat)-1.00000000000000022204,
  (OSQPFloat)-1.00000000000000022204,
};
OSQPCscMatrix data_A_csc = {
  2,
  4,
  data_A_csc_p,
  data_A_csc_i,
  data_A_csc_x,
  4,
  -1,
};
OSQPMatrix data_A = {
  &data_A_csc,
  0
};
OSQPFloat data_q_val[4] = {
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf data_q = {
  data_q_val,
  4
};
OSQPFloat data_l_val[2] = {
  (OSQPFloat)0.00446257167299544868,
  (OSQPFloat)-5.03716052589440543841,
};
OSQPVectorf data_l = {
  data_l_val,
  2
};
OSQPFloat data_u_val[2] = {
  (OSQPFloat)0.00446257167299544868,
  (OSQPFloat)-5.03716052589440543841,
};
OSQPVectorf data_u = {
  data_u_val,
  2
};
OSQPData data = {
  4,
  2,
  &data_P,
  &data_A,
  &data_q,
  &data_l,
  &data_u
};

/* Define the linear system solver structure */
OSQPInt linsys_L_p[7] = {
  0,
  1,
  2,
  2,
  3,
  4,
  4,
};
OSQPInt linsys_L_i[4] = {
  2,
  2,
  5,
  5,
};
OSQPFloat linsys_L_x[4] = {
  (OSQPFloat)-1.55368083619200469947,
  (OSQPFloat)-0.98541873801130119848,
  (OSQPFloat)-1.55368083619200469947,
  (OSQPFloat)-0.98541873801130119848,
};
OSQPCscMatrix linsys_L = {
  6,
  6,
  linsys_L_p,
  linsys_L_i,
  linsys_L_x,
  4,
  -1,
};
OSQPFloat linsys_Dinv[6] = {
  (OSQPFloat)1.55368083619200425538,
  (OSQPFloat)0.99999900000099983810,
  (OSQPFloat)-0.39451904218914735090,
  (OSQPFloat)1.55368083619200425538,
  (OSQPFloat)0.99999900000099983810,
  (OSQPFloat)-0.39451904218914735090,
};
OSQPInt linsys_P[6] = {
  2,
  0,
  4,
  3,
  1,
  5,
};
OSQPFloat linsys_bp[6];
OSQPFloat linsys_sol[6];
OSQPFloat linsys_rho_inv_vec[2] = {
  (OSQPFloat)0.01000000000000000021,
  (OSQPFloat)0.01000000000000000021,
};
OSQPInt linsys_KKT_p[7] = {
  0,
  1,
  2,
  5,
  6,
  7,
  10,
};
OSQPInt linsys_KKT_i[10] = {
  0,
  1,
  1,
  0,
  2,
  3,
  4,
  4,
  3,
  5,
};
OSQPFloat linsys_KKT_x[10] = {
  (OSQPFloat)0.64363283417394212549,
  (OSQPFloat)1.00000100000000013978,
  (OSQPFloat)-0.98541972343003936263,
  (OSQPFloat)-1.00000000000000022204,
  (OSQPFloat)-0.01000000000000000021,
  (OSQPFloat)0.64363283417394212549,
  (OSQPFloat)1.00000100000000013978,
  (OSQPFloat)-0.98541972343003936263,
  (OSQPFloat)-1.00000000000000022204,
  (OSQPFloat)-0.01000000000000000021,
};
OSQPCscMatrix linsys_KKT = {
  6,
  6,
  linsys_KKT_p,
  linsys_KKT_i,
  linsys_KKT_x,
  10,
  -1,
};
OSQPInt linsys_PtoKKT[4] = {
  1,
  6,
  0,
  5,
};
OSQPInt linsys_AtoKKT[4] = {
  2,
  7,
  3,
  8,
};
OSQPInt linsys_rhotoKKT[2] = {
  4,
  9,
};
OSQPFloat linsys_D[6] = {
  (OSQPFloat)0.64363283417394212549,
  (OSQPFloat)1.00000100000000013978,
  (OSQPFloat)-2.53473189646588004109,
  (OSQPFloat)0.64363283417394212549,
  (OSQPFloat)1.00000100000000013978,
  (OSQPFloat)-2.53473189646588004109,
};
OSQPInt linsys_etree[6] = {
  2,
  2,
  -1,
  5,
  5,
  -1,
};
OSQPInt linsys_Lnz[6] = {
  1,
  1,
  0,
  1,
  1,
  0,
};
QDLDL_int   linsys_iwork[18];
QDLDL_bool  linsys_bwork[6];
QDLDL_float linsys_fwork[6];
qdldl_solver linsys = {
  1,
  &name_qdldl,
  &solve_linsys_qdldl,
  &update_settings_linsys_solver_qdldl,
  &warm_start_linsys_solver_qdldl,
  &update_linsys_solver_matrices_qdldl,
  &update_linsys_solver_rho_vec_qdldl,
  1,
  &linsys_L,
  linsys_Dinv,
  linsys_P,
  linsys_bp,
  linsys_sol,
  linsys_rho_inv_vec,
  (OSQPFloat)0.00000100000000000000,
  (OSQPFloat)10.00000000000000000000,
  4,
  2,
  &linsys_KKT,
  linsys_PtoKKT,
  linsys_AtoKKT,
  linsys_rhotoKKT,
  linsys_D,
  linsys_etree,
  linsys_Lnz,
  linsys_iwork,
  linsys_bwork,
  linsys_fwork,
};

OSQPFloat work_rho_vec_val[2] = {
  (OSQPFloat)100.00000000000000000000,
  (OSQPFloat)100.00000000000000000000,
};
OSQPVectorf work_rho_vec = {
  work_rho_vec_val,
  2
};
OSQPFloat work_rho_inv_vec_val[2] = {
  (OSQPFloat)0.01000000000000000021,
  (OSQPFloat)0.01000000000000000021,
};
OSQPVectorf work_rho_inv_vec = {
  work_rho_inv_vec_val,
  2
};
OSQPInt work_constr_type_val[2] = {
  1,
  1,
};
OSQPVectori work_constr_type = {
  work_constr_type_val,
  2
};
OSQPFloat work_x_val[4] = {
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf work_x = {
  work_x_val,
  4
};
OSQPFloat work_y_val[2] = {
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf work_y = {
  work_y_val,
  2
};
OSQPFloat work_z_val[2] = {
  (OSQPFloat)0.00000000000000000000,
  (OSQPFloat)0.00000000000000000000,
};
OSQPVectorf work_z = {
  work_z_val,
  2
};
OSQPFloat   work_xz_tilde_val[6];
OSQPVectorf work_xz_tilde = {
  work_xz_tilde_val,
  6
};
OSQPVectorf work_xtilde_view = {
  work_xz_tilde_val,
  4
};
OSQPVectorf work_ztilde_view = {
  work_xz_tilde_val+4,
  2
};
OSQPFloat   work_x_prev_val[4];
OSQPVectorf work_x_prev = {
  work_x_prev_val,
  4
};
OSQPFloat   work_z_prev_val[2];
OSQPVectorf work_z_prev = {
  work_z_prev_val,
  2
};
OSQPFloat   work_Ax_val[2];
OSQPVectorf work_Ax = {
  work_Ax_val,
  2
};
OSQPFloat   work_Px_val[4];
OSQPVectorf work_Px = {
  work_Px_val,
  4
};
OSQPFloat   work_Aty_val[4];
OSQPVectorf work_Aty = {
  work_Aty_val,
  4
};
OSQPFloat   work_delta_y_val[2];
OSQPVectorf work_delta_y = {
  work_delta_y_val,
  2
};
OSQPFloat   work_Atdelta_y_val[4];
OSQPVectorf work_Atdelta_y = {
  work_Atdelta_y_val,
  4
};
OSQPFloat   work_delta_x_val[4];
OSQPVectorf work_delta_x = {
  work_delta_x_val,
  4
};
OSQPFloat   work_Pdelta_x_val[4];
OSQPVectorf work_Pdelta_x = {
  work_Pdelta_x_val,
  4
};
OSQPFloat   work_Adelta_x_val[2];
OSQPVectorf work_Adelta_x = {
  work_Adelta_x_val,
  2
};
OSQPFloat   work_D_temp_val[4];
OSQPVectorf work_D_temp = {
  work_D_temp_val,
  4
};
OSQPFloat   work_D_temp_A_val[4];
OSQPVectorf work_D_temp_A = {
  work_D_temp_A_val,
  4
};
OSQPFloat   work_E_temp_val[2];
OSQPVectorf work_E_temp = {
  work_E_temp_val,
  2
};

/* Define the scaling structure */
OSQPFloat scaling_D_val[4] = {
  (OSQPFloat)0.70710678118654757274,
  (OSQPFloat)0.70710678118654757274,
  (OSQPFloat)17.93922844179678932619,
  (OSQPFloat)17.93922844179678932619,
};
OSQPVectorf scaling_D = {
  scaling_D_val,
  4
};
OSQPFloat scaling_E_val[2] = {
  (OSQPFloat)1.39359393750470594853,
  (OSQPFloat)1.39359393750470594853,
};
OSQPVectorf scaling_E = {
  scaling_E_val,
  2
};
OSQPFloat scaling_Dinv_val[4] = {
  (OSQPFloat)1.41421356237309492343,
  (OSQPFloat)1.41421356237309492343,
  (OSQPFloat)0.05574375750018824294,
  (OSQPFloat)0.05574375750018824294,
};
OSQPVectorf scaling_Dinv = {
  scaling_Dinv_val,
  4
};
OSQPFloat scaling_Einv_val[2] = {
  (OSQPFloat)0.71756913767187158193,
  (OSQPFloat)0.71756913767187158193,
};
OSQPVectorf scaling_Einv = {
  scaling_Einv_val,
  2
};
OSQPScaling scaling = {
  (OSQPFloat)1.00000000000000000000,
  &scaling_D,
  &scaling_E,
  (OSQPFloat)1.00000000000000000000,
  &scaling_Dinv,
  &scaling_Einv
};

/* Define the workspace structure */
OSQPWorkspace work = {
  &data,
  (LinSysSolver *)&linsys,
  &work_rho_vec,
  &work_rho_inv_vec,
  &work_constr_type,
  &work_x,
  &work_y,
  &work_z,
  &work_xz_tilde,
  &work_xtilde_view,
  &work_ztilde_view,
  &work_x_prev,
  &work_z_prev,
  &work_Ax,
  &work_Px,
  &work_Aty,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  &work_delta_y,
  &work_Atdelta_y,
  &work_delta_x,
  &work_Pdelta_x,
  &work_Adelta_x,
  &work_D_temp,
  &work_D_temp_A,
  &work_E_temp,
  &scaling,
  (OSQPFloat)0.0,
  (OSQPFloat)0.0,
  (OSQPFloat)0.00000000000000000000,
  0,
  (OSQPFloat)1000000000000000019884624838656.00000000000000000000,
};

/* Define the solver structure */
OSQPSolver solver = {
  &settings,
  &sol,
  &info,
  &work
};
